version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13-browsers
    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install project package
          command: |
            set +o pipefail
            yes n | npm ci
      ## Test
      - run:
          name: Linting
          command: npm run lint

      ## Build
      - run:
          name: Building the package
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: AWS S3
          command: aws s3 sync ~/project/dist s3://sorcererdecks.com/ --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master